### ISSUE TITLE
Support Cancel method generation for lro

### ISSUE THREAD

**Issue by hwen-cb** [googleapis/gapic-generator-go#1391]
**Is your feature request related to a problem? Please describe.**
The current [lro generation logic](https://github.com/googleapis/gapic-generator-go/blob/98f6d72bdb9e06d0e3ab4e34572c3896e06b4766/internal/gengapic/lro.go#L179-L206) does not support generating the [Cancel method ](https://github.com/googleapis/google-cloud-go/blob/6fedb83392aac87bcb47986637e17ca50c2146af/longrunning/longrunning.go#L170) which is a standard method for LRO. We need the functionality for generating it which we will use in our generated client.

Also wondering if there is a specific reason that this has not been supported by now.
**Describe the solution you'd like**
Add support for generating the Cancel method, which should be a pretty lightweight lift, similar to other methods.

**Describe alternatives you've considered**
Can also consider supporting generating Cancel method optionally, controlled by a config/argument, if there is a reason why this has not been supported.

**Additional context**
Also happy to bring up a PR for review if the above sounds good.

**Comment by noahdietz** [comment]
Thanks for the issue!

> wondering if there is a specific reason that this has not been supported by now.

Until recently, we had no configuration to indicate which services actually supported `CancelOperation` - believe it or not, not every service that has Operations also has CancelOperation support.

> generating the Cancel method, which should be a pretty lightweight lift,

You are right, it would be very straight forward.

> Can also consider supporting generating Cancel method optionally

We'd need this, yes.

> controlled by a config

I'll be honest, the only configuration we'd really look at to support this is if the `google.api.Service` config indicated that it supported the `CancelOperation` method. The signal there is if the `http.rules` aspect contains an override for `google.longrunning.CancelOperation` ([example](https://github.com/googleapis/googleapis/blob/01f6828d2b8868fc9d314f9ac86677d3253fa33b/google/cloud/tpu/v1/tpu_v1.yaml#L40-L41)). I don't know if you use that configuration, but if you do, then great let's do it. Otherwise, I think we are out of luck. We really can't accept anymore configuration sources.

**Comment by hwen-cb** [comment]
Thank you for the prompt response!

We do not explicitly specify the CancelOperation (or any LRO method) in our service proto config. Our project is composed of multiple services, and for each of them we wrap the server with a same LROServer on the service side to handle all the lro operations. 

In the LROServer we also wrap each LRO with a custom operation type, and have an allowlist to determine which operation types can be cancelled. On the client side we just want to generate the Cancel method for all LROs similar to other LRO methods. If clients call Cancel on a LRO that does not support it, our service side would just return a 400 based on the allowlist which is fine.

Ideally a simple argument to decide whether to generate the Cancel method for all operations would be sufficient, but totally understand if you cannot accept more configurations like that. Wondering if you see any other workaround for our use case? Another option is to fork the repo but would like to do that as a last resort.

**Comment by noahdietz** [comment]
> Thank you for the prompt response!

FYI: I'll be ooo for the next week :)

> Ideally a simple argument to decide whether to generate the Cancel method for all operations would be sufficient

Ah yeah see it could be that easy, but the tricky part there is that since this generates clients for both REST and gRPC transports, we *need* the HTTP binding I mentioned earlier to generate a REST client. If we use a flag to toggle instead, we have no guarantee that the HTTP binding is there. Extra validation, combined with checking against desired transports means that we have a bit of an bump in complexity.

The most robust solution would be to reference the service configuration as I mentioned...

> Wondering if you see any other workaround for our use case?

Only other one is outside of the generator - just add manual code to the packages that want a Cancel method. For example, we discontinued some automation that exported the `setGoogleClientInfo` on each generated client that wanted it exported. We replaced with with a manually written file [like this](https://github.com/googleapis/google-cloud-go/blob/main/bigquery/storage/apiv1/info.go) that lives along side the generated code, in the same package, and augments the generated client. You could do the same with adding the `Cancel` method to any operation wrapper your generated clients have.

**Comment by hwen-cb** [comment]
Thanks for the response, and yeah that makes sense! The issue with manually adding the Cancel method for certain operations is that we actually have also added an interface on the client side for all the operations so users can invoke the LRO methods using that easily without worrying about connecting to the LRO server which is separate from each of our proto service server. 

So basically we need to add the Cancel method for every operation on the client side and only do the filtering on the server side. We've decided to fork this repo and it has been working well based on initial testing. Thank you for your quick responses and help, and hope you enjoy a nice week off :)
