### ISSUE TITLE
gapic: clients should set a default timeout in the generated code based on the generation config (cloud spanner)

### ISSUE THREAD

**Issue by hengfengli** [googleapis/gapic-generator-go#411]
## Issue

We found that the generated code does not have any default timeout settings from config files. 

Config files: 

* https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_grpc_service_config.json
* https://github.com/googleapis/googleapis/blob/master/google/spanner/admin/database/v1/spanner_admin_database_grpc_service_config.json
* https://github.com/googleapis/googleapis/blob/master/google/spanner/admin/instance/v1/spanner_admin_instance_grpc_service_config.json

Generated code: 

- Spanner client: https://github.com/googleapis/google-cloud-go/blob/master/spanner/apiv1/spanner_client.go#L68
- DB admin client: https://github.com/googleapis/google-cloud-go/blob/master/spanner/admin/database/apiv1/database_admin_client.go#L74
- Instance admin client: https://github.com/googleapis/google-cloud-go/blob/master/spanner/admin/instance/apiv1/instance_admin_client.go#L67

## Actual behaviour

No default timeouts. 

## Expected behaviour

All grpc methods should respect the default timeout settings from the config files. 

## Notes

I had a brief discussion with @noahdietz: "It is possible to explore a solution that if the context does not have any user-specified timeout, we should assign a default timeout. However, this could be perceived as a breaking change for Go GAPICs - where an RPC would happily hang until completion, now it is canceling and returning an error. Users might not be prepared for that."

We expect the timeout/retrying settings should be consistent across all languages. However, in terms of timeout settings, Go client lib is inconsistent. The spanner client lib dev team hopes this can be fixed.

**Comment by noahdietz** [comment]
Hi @hengfengli thanks for opening this so that we can formally discuss it. I would like to clarify that this is not an "issue" (or bug) as stated. It is a design decision based on the common practice of Go users managing their `Context` and deadlines.

Now, supporting this using [`context.WithDeadline()`](https://pkg.go.dev/context?tab=doc#WithDeadline) might be OK, per this part of the docs:

    If the parent's deadline is already earlier than d, WithDeadline(parent, d) is semantically equivalent to parent

So we won't disturb anyone's existing deadline by setting a default one. But, like I said offline, this could be considered a breaking change in behavior for those not managing their `Context` deadline.

What do others think? @broady @tbpg @codyoss

**Comment by noahdietz** [comment]
FWIW the current behavior is documented in the (top-level) module docs ([here](https://pkg.go.dev/cloud.google.com/go?tab=doc#hdr-Timeouts_and_Cancellation)) and each of the client packages reference that documentation ([here](https://pkg.go.dev/cloud.google.com/go/spanner/apiv1?tab=doc#hdr-Use_of_Context)).

**Comment by noahdietz** [comment]
This was discussed in our regular sync and folks are interested in supporting this. I think the next step is to come up with a design and review it with the team. Such a design should include a rollout plan/communication strategy to users as well as contributing teams.

**Comment by tritone** [comment]
One semi-related note that I discussed with @noahdietz -- in the storage client (which is still on HTTP), we had a few customer issues come in where customers were surprised that methods could hang indefinitely unless a context deadline was set. I ended up adding setting a context deadline to our code samples for storage as an education effort (see GoogleCloudPlatform/golang-samples#1173).

**Comment by noahdietz** [comment]
Circling back here, we have reached agreement on a default deadline design, which is implemented and roughly outlined in #422. The default deadline will be a _logical call deadline_ - the time allowed for the method/stream to execute _overall_, regardless of how many RPC attempts are made by the method. This aligns the best with the existing deadline support via the `context` provided to each method and with what we want to do in other GAPIC languages.

Note: we are omitting Paginated methods from this first pass as there are some specific design decisions that need to be made about Iterator vs. per-Iteration deadline configurability (today there is only Iterator-level configurability via the `context` used to create an Iterator).

**Comment by noahdietz** [comment]
After another review we punted on adding default deadlines to Streaming RPCs in #422, not feeling confident that in some cases where long-lived streams are common or there is a different deadline model (e.g. pubsub message ack) this change would be work properly. 

The work remaining to fully close this issue is to support default deadlines for:
* paginated methods
* server-streaming methods
* client-streaming methods
* bi-di streaming methods

Either an implementation or a concrete decision not to implement is needed for each.

**Comment by noahdietz** [comment]
Furthermore, an opt-out mechanism was introduced as a break-glass for users that are caught off guard by the change. It should be removed once everything is fully resolved and has baked. It is an environment variable check on client-initialization that applies to the life of that client isntance.

**Comment by codyoss** [comment]
Need to remove an opt-out envvar still.
