### ISSUE TITLE
protoc-gen-go_gapic: support strip-module prefix option

### ISSUE THREAD

**Issue by valery-barysok** [googleapis/gapic-generator-go#447]
Could you support `module` option like in `protoc-gen-go` and `protoc-gen-go-grpc` plugins.

```
	protoc \
		-I ${API_COMMON_PROTOS} \
		-I ${EXAMPLEAPIS} \
		--go_gapic_out=. \
                --go_gapic_opt=module=github.com/example/repo \
		--go_gapic_opt="go-gapic-package=github.com/example/repo/myapi/apiv1"';myapi' \
		${EXAMPLEAPIS}/myapi/v1/*.proto
```

should generate next structure:

```
.
|_myapi
   |_apiv1
      |_doc.go
      |_example_client.go
      |_example_client_example_test.go
```

but in the same time `example_client_example_test.go` should have next import:

```
import myapi "github.com/example/repo/myapi/apiv1"
```

instead of

```
import myapi "myapi/apiv1"
```

**Comment by noahdietz** [comment]
If I understand this (correct me if I don't), you'd like to see a `module` option that defines the module prefix of the generated Go module that should be stripped from the output file name, thus making protoc drop the file in that relative path, rather than in the module (import)path. Implemented [here](https://go-review.googlesource.com/c/protobuf/+/219298/) by protoc-gen-go.

That sounds useful to me. Sure. I'll about adding that in there soon. I will follow up on this issue with updates.

**Comment by valery-barysok** [comment]
@noahdietz, you are right. thanks.

**Comment by noahdietz** [comment]
Just decided to do it in #448
