### ISSUE TITLE
gapic: are auth tokens intentionally stripped from insecure connections?

### ISSUE THREAD

**Issue by timburks** [googleapis/gapic-generator-go#542]
I'm working in a team that's building a public and open source gRPC API (https://github.com/apigee/registry), and we've found that our gapic-based API clients don't work when we connect insecurely to a server that expects an authorization token - I believe that something deep in the underlying gax or grpc code is stripping these (as a benefit to users?).

I've worked around this by creating a modified "doc.go" for our gapics that [explicitly adds our auth token to the request metadata](https://github.com/apigee/registry/blob/a4eed9fb92c9089d8cfa2c16e3568694bf11fb0d/cmd/authz-server/gapic-insecure/doc.go#L57). This is ugly - as it's currently written, it breaks authentication for secure calls (I believe because the token gets added twice), and it requires updating whenever the generated doc.go changes.

Do you have any suggestions for a better way to handle this? I think we'd be happy if these tokens were always included - that's what we want for testing, and we may also be using gapics in secured clusters over HTTP only (without HTTPS) - but an option to include them would also be ok, or just having a better way to do this than the hacky code that I've linked above.

/cc @seaneganx

**Comment by noahdietz** [comment]
Ok. When you say "connect insecurely" do you mean supplying the client [grpc.WithInsecure](https://pkg.go.dev/google.golang.org/grpc#WithInsecure)? Or are you dialing your own connection via [transport.DialGRPCInsecure](https://pkg.go.dev/google.golang.org/api/transport#DialGRPCInsecure) and supplying the raw connection to the client?

If you are using Google Application Default creds in the "secure" case, then that will certainly not be loaded automatically when dialing an insecure connection. The code path to load ADC is [not executed in Insecure mode](https://github.com/googleapis/google-api-go-client/blob/7fd7a5fcdd3f78a6c49556a5358164cb1405bd51/transport/grpc/dial.go#L122-L169).

I'm not 100% sure but supplying an authentication option while using Insecure _may_ be disallowed at the gRPC level, so that may rule out using something like [option.WithTokenSource](https://pkg.go.dev/google.golang.org/api/option#WithTokenSource). It could be worth trying though. You can author a "client hook"  for the gapic in a snippet of manual code that lives in the same pkg as the generated client (see [wiki](https://github.com/googleapis/google-cloud-go/wiki/Customizing-constructors)) to supply the client option `WithTokenSource` with the token loaded from the environment kind of like how you're doing directly on the metadata. Using the client constructor hook doesn't help with metadata injection though. 

But another question is, why is your server expecting a token when receiving traffic on an insecure connection? Seems, well, insecure.

**Comment by timburks** [comment]
I think we are using Application Default Credentials - we're using the same authentication as the generated CLIs (and we're using the generated CLIs). This is happening only during testing but has come up at least twice. We set up a container that contains token-checking code and run it outside Cloud Run or some other wrapper that provides SSL termination, and requests mysteriously fail until we realize that auth tokens aren't being sent.

[Here](https://github.com/apigee/registry/blob/4db91e07849992372b45dc295a7a642a9fb1232c/connection/client.go#L66) is where we're making our connections, but this is only used in our handwritten clients and not our generated CLI.

**Comment by timburks** [comment]
The hook option is nice but I see the problem: if we try to send an `option.WithCredentials` back from the hook, it collides with the default credentials and we get an error "multiple credential options provided"

**Comment by noahdietz** [comment]
The generated CLIs de[pend on the GAPIC to load ADC, unless the user provides some token via a flag or env var.

[Looks like](https://github.com/googleapis/google-api-go-client/blob/1a7550f9546052997806ff7ea9bcba55326bdb16/internal/settings.go#L94-L96) only `option.WithTokenSource` and `option.WithCredentialsFile` are allow-listed when it comes to overriding credentials.

Another thing you can try is back all the way up and create your own gRPC connection, then supply that to the client via [`option.WithGRPCConn`](https://pkg.go.dev/google.golang.org/api/option#WithGRPCConn).

**Comment by timburks** [comment]
This was my hook, btw (which produced the error):
```
package gapic

import (
        "context"
        "os"

        "google.golang.org/api/option"
                "golang.org/x/oauth2/google"

        "golang.org/x/oauth2"
)

func init() {
        newRegistryClientHook = func(ctx context.Context, p clientHookParams) ([]option.ClientOption, error) {
                insecure := os.Getenv("APG_REGISTRY_INSECURE")
                token := os.Getenv("APG_REGISTRY_TOKEN")
                if insecure == "1" && token != "" {
                        credentials := &google.Credentials{TokenSource:oauth2.StaticTokenSource(&oauth2.Token{AccessToken:token})}
                        return []option.ClientOption{
                            option.WithCredentials(credentials),
                        }, nil
                }

                return nil, nil
        }
}
```

**Comment by timburks** [comment]
> Another thing you can try is back all the way up and create your own gRPC connection, then supply that to the client via option.WithGRPCConn.

Conveniently, I think [we've already done that](https://github.com/apigee/registry/blob/4db91e07849992372b45dc295a7a642a9fb1232c/connection/client.go#L40) so that our handwritten tools could authenticate with the same environment variables, but since this wouldn't fix the generated client, I didn't think of adding the token there.

**Comment by timburks** [comment]
I'm not sure that I want to use this, but it seems to work:
```
sed -i 's/return metadata.NewOutgoingContext(ctx, out)/insecure := os.Getenv("APG_REGISTRY_INSECURE")\ntoken := os.Getenv("APG_REGISTRY_TOKEN")\nif insecure == "1" \&\& token != "" \{ \nout["authorization"] = append(out["authorization"], "Bearer "+token) \n\}\nreturn metadata.NewOutgoingContext(ctx, out)/' gapic/doc.go
gofmt -w gapic/doc.go
```

That inserts the five lines below into `insertMetadata` in the generated doc.go.
```
        insecure := os.Getenv("APG_REGISTRY_INSECURE")
        token := os.Getenv("APG_REGISTRY_TOKEN")
        if insecure == "1" && token != "" {
                out["authorization"] = append(out["authorization"], "Bearer "+token)
        }
```

**Comment by noahdietz** [comment]
@timburks have you been able to work around this or find a solution? The GAPIC stack is WAI so I'd like to close this if possible.

**Comment by timburks** [comment]
@noahdietz We're using the workaround that I mentioned above.

**Comment by noahdietz** [comment]
I'm going to close this because the gapics don't do anything here, but rather the transport library, and the question has been discussed with a workaround described.
