### ISSUE TITLE
Docker file and gapic.sh scripts fail with invalid plugin option format

### ISSUE THREAD

**Issue by mscno** [googleapis/gapic-generator-go#558]
# What happened
When running the gapic.sh script or the Docker image, the following error is returned:

`--go_gapic_out: invalid plugin option format, must be key=value: `

# What did you expect
Sucessful generation of the client

# Issue cause
I suspect that this is caused by incorrect passing of the $OUT argument in line 57 of the docker entrypoint:
https://github.com/googleapis/gapic-generator-go/blob/edf7f967d47fd97b57d5ce72a8cd932040c3eb1a/docker-entrypoint.sh#L57

**Comment by noahdietz** [comment]
Can you share your invocation of the script? 

Thanks for the suggestion, but actually that line is correct - that is the protoc option to indicate the `protoc-gen-go_gapic` plugin should be invoked and that its output should be written to the given directory.

The error message is because of the plugin option flags - those that start with `--go_gapic_opt`. A single letter difference there :)

**Comment by mscno** [comment]
Sure, I invoke the script like so:

```sh
docker run \
  --rm \
  --user $UID \
  --mount type=bind,source=$(pwd)/rpc/services/entities/v3/,destination=/in/,readonly \
  --mount type=bind,source=$(pwd)/gapic/go/gen/,destination=/out/ \
  gcr.io/gapic-images/gapic-generator-go \
  --go-gapic-package "gapic/go/gen;goclient"
```

**Comment by noahdietz** [comment]
I know the issue - the generator is parsing empty options incorrectly. The script is sending `--go_gapic_opt=` because some optional flags are not provided and it doesn't check for that. It's a simple fix in the generator, but it will take a little time to get the image rebuilt and published.

**Comment by noahdietz** [comment]
Try `gcr.io/gapic-images/gapic-generator-go:0.18.5`.
