### ISSUE TITLE
Support for go_package defined via opt `Mpath/to/file.proto=this.is/my/go/pkg`

### ISSUE THREAD

**Issue by sgtsquiggs** [googleapis/gapic-generator-go#753]
I currently determine go_package names at build time and do not persist the option in my proto files. This works well with `protoc-gen-go` and `protoc-gen-go-grpc` but `protoc-gen-go_gapic` does not seem to respect these options. Is there a hidden option I need to use or does gapic codegen not support this?

**Comment by noahdietz** [comment]
Thanks @sgtsquiggs for the reference. I agree that we should support this, since this generator is meant to be used in conjunction with the protobuf/grpc output. I've changed this to a feature request, albeit a lower priority one.

If you are interested in contributing a PR for this, it would be welcome. I think we'd need to 1. add plugin option to match 2. collect the mapping of file-to-package from the option at runtime 3. essentially inject the `go_package` option with the appropriate value on the appropriate files _before_ the generator parses the descriptor set (the call to `pbinfo.Of(files)`). That way, the rest of the generator stack should "just work" as if the proto was annotated in source.

LMK if you'd like to contribute, otherwise I will try to find someone/some time to add this.

Note: this generator has not been migrated to the protobuf-go v2 compiler plugin interface.

**Comment by sgtsquiggs** [comment]
Perhaps code from the older protoc-gen-go can make this easier: https://github.com/golang/protobuf/blob/84668698ea25b64748563aa20726db66a6b8d299/protoc-gen-go/generator/generator.go#L666

**Comment by noahdietz** [comment]
Forgot to tag this issue. Fixed by https://github.com/googleapis/gapic-generator-go/pull/1029. Must provide `--go_gapic_opt=Mpath/to/my.proto=import/path/override`.
