### ISSUE TITLE
gapic: REGAPIC clients don't return gRPC status codes (maybe they should)

### ISSUE THREAD

**Issue by timburks** [googleapis/gapic-generator-go#827]
I have a set of tests that use gRPC and REST GAPICS to call an API that is directly served and transcoded to HTTP by Envoy. These tests compile and make calls identically over both transports (🎉) but I noticed that calls that return "not found" errors get [GRPCStatus](https://github.com/grpc/grpc-go/blob/aff571cc86e6e7e740130dbbb32a9741558db805/status/status.go#L107) errors (e.g. ones where `status.Code(err) == codes.NotFound`) over gRPC and [`googleapi.Error`](https://github.com/googleapis/google-api-go-client/blob/2311ef1bb8fb243771800754ba6c54e9d0bf3a67/googleapi/googleapi.go#L146) values over HTTP transports. 

It would be nice for callers if both transports returned consistent error structures. It might be a bit surprising for the HTTP transport to return `GRPCStatus`-based errors, but OTOH all of the other calling conventions appear to be consistent with the gRPC interface and the benefits of full drop-in compatibility seem high.

Currently the generated REST clients use `googleapi.CheckResponse` which is difficult (probably impossible) to change since it has [been around a while](https://github.com/googleapis/google-api-go-client/blob/2311ef1bb8fb243771800754ba6c54e9d0bf3a67/googleapi/googleapi.go#L1) (so it might need to be replaced in the generated REST clients).

**Comment by noahdietz** [comment]
Yes, so at the moment, the `googleapi.Error` types are being returned directly, but in the not-so-distant future we will want to wrap those in the [`APIError`](https://pkg.go.dev/github.com/googleapis/gax-go/v2/apierror#APIError). Folks using the [`errors.As`](https://pkg.go.dev/errors#As) API to (possibly) extract a `googleapi.Error` from the `error` returned will still get the proper error. In there is where we may be able to do some "code translation" behind a `Code()` API, that returns the status code in terms of whatever we want. 

This is something we have to solve in order to provide retry logic for REGAPIC clients, which currently isn't supported because calls for REGAPICs don't run through `gax.Invoke` yet.

**Comment by noahdietz** [comment]
Blocked by #842

**Comment by timburks** [comment]
OK, I see that the gRPC GAPICs are currently returning `APIError` values, but to identify the type of the error ("NotFound") I'm checking the wrapped gRPC status code. I don't mind changing that to check the error type in a different way, but I'm hoping that both HTTP and gRPC responses can be checked in the same way - i.e. that an HTTP "NotFound" can be recognized in the same way that a gRPC "NotFound" is recognized. Looking over the `APIError` docs, I haven't yet seen how I would do that.

**Comment by noahdietz** [comment]
There isn't currently a "generic" code checking interface in `APIError`, and there probably should be, that's what I mean in my comment. We at least have a common error wrapper to work within.

**Comment by noahdietz** [comment]
Ok so we are _not_ going to present a transport agnostic status code concept here. I will close this for now, but it can be reopened in the future.

The reason is that we don't want to make too many abstractions in the Go clients, and we are committed to retaining the gRPC and HTTP specific option support in Go, so there will always be a little bit of "transport leak" above the interface. We've added an `OnHTTPCodes` retryer to gax-go, and utilize the `net/http` constants to make the generated code more readable.
